config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'articles#index'
  devise_for :users
  resources :comments
  resources :articles
  resources :users, only: %i[index show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  message    :text
#  visible    :boolean          default(FALSE)
#  article_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Comment < ApplicationRecord
  extend FriendlyId

  belongs_to :article
  belongs_to :user

  friendly_id :uuid, use: [:slugged,:finders]

  before_create :generate_uuid
  after_create :manually_update_slug
  validates :message, presence: true

  def generate_uuid
    self.uuid = "#{self.model_name.name}-" + SecureRandom.uuid
    p "Comment UUID- #{self.uuid} has been created"
  end

  def manually_update_slug
    self.update_column(:slug,self.uuid)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  message    :text
#  visible    :boolean          default(FALSE)
#  article_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class CommentsController < ApplicationController
  before_action :set_comment, only: %i[show edit update destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.paginate(page: params[:page], per_page: params[:per_page] ||= 30).order(created_at: :desc)
    respond_to do |format|
      format.json { render json: Comment.all }
      format.html {}
    end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    respond_to do |format|
      format.json { render json: @comment }
      format.html { @comment }
    end
  end

  #   @comment = Comment.friendly.find(params[:id])
  # end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit; end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    # respond_to do |format|
    #   if @comment.save
    #     format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
    #     format.json { render :show, status: :created, location: @comment }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @comment.errors, status: :unprocessable_entity }
    #   end
    # end
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :bad_request }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    # respond_to do |format|
    #   if @comment.update(comment_params)
    #     format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @comment }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @comment.errors, status: :unprocessable_entity }
    #   end
    # end
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render json: @comment, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :bad_request }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end

  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    begin
    @comment = Comment.friendly.find(params[:id])
   rescue
     respond_to do |format|
       format.html { redirect_to comments_path, alert: 'Comment Not Found' }
       format.json { render status: 404, json: {alert: 'Comment Not Found'} }
     end
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:message, :visible, :article_id, :user_id)
    # Students, make sure to add the user_id and article ID parameter as symbols here ^^^^^^
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  message    :text
#  visible    :boolean          default(FALSE)
#  article_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message %>
    <%= form.text_area :message, id: :comment_message %>
  </div>

  <div class="field">
    <%= form.label :visible %>
    <%= form.check_box :visible, id: :comment_visible %>
  </div>

  <div class="field">
    <%= form.collection_select :article_id, Article.all, :id, :title %>
  </div>

  <div class="field">
    <%= form.collection_select :user_id, User.all, :id, :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 well">
    <h1>Editing Comment</h1>

    <%= render 'form', comment: @comment %>

    <%= link_to 'Show', @comment %> |
    <%= link_to 'Back', comments_path %>
  </div>
</div>

app/views/comments/index.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1>Comments</h1>
        <%= will_paginate @comments %>
      </div>

      <table class="table table-hover">
        <thead>
        <tr>
          <th>Message</th>
          <th colspan="3"></th>
        </tr>
        </thead>

        <tbody>
        <% @comments.each do |comment| %>
          <tr>
            <td><%= comment.message %></td>
            <td><%= link_to 'Show', comment %></td>
            <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
            <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <div class="panel-footer">
        <%= link_to 'New Comment', new_comment_path, class: 'btn btn-success' %>
        <%= page_entries_info @comments %>
      </div>

    </div>
  </div>
</div>

app/views/comments/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2 well">
    <h1>New Comment</h1>

    <%= render 'form', comment: @comment %>

    <%= link_to 'Back', comments_path %>
  </div>
</div>

app/views/comments/show.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-success">
      <div class="panel-heading">
        Article
      </div>

      <div class="panel-body">
        <p>
          <strong>Message:</strong>
          <%= @comment.message %>
        </p>

        <p>
          <strong>Visible:</strong>
          <%= @comment.visible %>
        </p>

        <p>
          <strong>Article:</strong>
          <%= link_to @comment.article.title, @comment.article %>
        </p>

        <p>
          <strong>Author:</strong>
          <%= link_to @comment.user.email, @comment.user %>
        </p>
      </div>

      <div class="panel-footer">
        <%= link_to 'Edit', edit_comment_path(@comment), class: "btn btn-success" %>
        <%= link_to 'Back', comments_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>