config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'articles#index'
  devise_for :users
  resources :comments
  resources :articles
  resources :users, only: %i[index show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash.html.erb
<%# Notice %>
<% if flash[:notice] %>
  <div id="flash" data-type="notice" class="alert-success" ><%= notice %></div>
<% end %>

<%# Warning %>
<% if flash[:warning] %>
  <div id="flash" data-type="warning" class="alert-warning"><%= warning %></div>
<% end %>

<%# Alert %>
<% if flash[:alert] %>
  <div id="flash" data-type="alert" class="alert-danger"><%= alert %></div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Legit News", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to "Articles", articles_path %></li>
      <li><%= link_to "Comments", comments_path %></li>
      <li><%= link_to "Users", users_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Edit User", edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: 'delete' %></li>
      <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>